Sparkplug B C++ Library: sparkplug::Publisher Class Reference
sparkplug::Publisher Class Reference
Sparkplug B edge node publisher implementing the complete message lifecycle.
#include <publisher.hpp>
Classes
struct Config
Configuration parameters for the Sparkplug B publisher.
Public Member Functions
Publisher (Config config)
Constructs a Publisher with the given configuration.
~Publisher ()
Destroys the Publisher and cleans up MQTT resources.
Publisher (const Publisher &)=delete
Publisher & operator= (const Publisher &)=delete
Publisher (Publisher &&) noexcept
Publisher & operator= (Publisher &&) noexcept
std::expected< void, std::string > connect ()
Connects to the MQTT broker and establishes a Sparkplug B session.
std::expected< void, std::string > disconnect ()
Gracefully disconnects from the MQTT broker.
std::expected< void, std::string > publish_birth (PayloadBuilder &payload)
Publishes an NBIRTH (Node Birth) message.
std::expected< void, std::string > publish_data (PayloadBuilder &payload)
Publishes an NDATA (Node Data) message.
std::expected< void, std::string > publish_death ()
Publishes an NDEATH (Node Death) message.
std::expected< void, std::string > rebirth ()
Triggers a rebirth by publishing a new NBIRTH with incremented bdSeq.
uint64_t get_seq () const
Gets the current message sequence number.
uint64_t get_bd_seq () const
Gets the current birth/death sequence number.
std::expected< void, std::string > publish_device_birth (std::string_view device_id, PayloadBuilder &payload)
Publishes a DBIRTH (Device Birth) message.
std::expected< void, std::string > publish_device_data (std::string_view device_id, PayloadBuilder &payload)
Publishes a DDATA (Device Data) message.
std::expected< void, std::string > publish_device_death (std::string_view device_id)
Publishes a DDEATH (Device Death) message.
std::expected< void, std::string > publish_node_command (std::string_view target_edge_node_id, PayloadBuilder &payload)
Publishes an NCMD (Node Command) message to another edge node.
std::expected< void, std::string > publish_device_command (std::string_view target_edge_node_id, std::string_view target_device_id, PayloadBuilder &payload)
Publishes a DCMD (Device Command) message to a device on another edge node.
Detailed Description
Sparkplug B edge node publisher implementing the complete message lifecycle.
The Publisher class manages the full Sparkplug B protocol for an edge node:
NBIRTH: Initial birth certificate with all metrics and aliases
NDATA: Subsequent data updates using aliases for bandwidth efficiency
NDEATH: Death certificate (sent via MQTT Last Will Testament)
Automatic sequence number management (0-255, wraps at 256)
Birth/Death sequence (bdSeq) tracking for session management
Thread Safety
This class is NOT thread-safe. All methods must be called from the same thread.
Example Usage
sparkplug::Publisher::Config config{
  .broker_url = "tcp://localhost:1883",
  .client_id = "my_edge_node",
  .group_id = "Energy",
  .edge_node_id = "Gateway01"
};
sparkplug::Publisher publisher(std::move(config));
publisher.connect();
// Publish NBIRTH (required first message)
sparkplug::PayloadBuilder birth;
birth.add_metric_with_alias("Temperature", 1, 20.5);
publisher.publish_birth(birth);
// Publish NDATA updates
sparkplug::PayloadBuilder data;
data.add_metric_by_alias(1, 21.0);  // Temperature changed
publisher.publish_data(data);
publisher.disconnect();  // Sends NDEATH automatically
See also
PayloadBuilder for constructing metric payloads
Subscriber for consuming Sparkplug B messages
Definition at line 58 of file publisher.hpp.
Constructor & Destructor Documentation
Publisher()
sparkplug::Publisher::Publisher (Config config)
Constructs a Publisher with the given configuration.
Parameters
config Publisher configuration (moved)
Note
The NDEATH payload is prepared during construction and will be sent automatically when the MQTT connection is lost.
Referenced by ~Publisher().
Member Function Documentation
connect()
std::expected< void, std::string > sparkplug::Publisher::connect () nodiscard
Connects to the MQTT broker and establishes a Sparkplug B session.
Sets the NDEATH message as the MQTT Last Will Testament before connecting. The NDEATH will be sent automatically if the connection is lost unexpectedly.
Returns
void on success, error message on failure
Note
Must be called before publish_birth().
Warning
The Publisher must remain in scope while connected, or NDEATH may not be delivered properly.
References connect().
Referenced by connect().
disconnect()
std::expected< void, std::string > sparkplug::Publisher::disconnect () nodiscard
Gracefully disconnects from the MQTT broker.
Sends NDEATH via MQTT Last Will Testament and closes the connection.
Returns
void on success, error message on failure
Note
After disconnect, you can call connect() again to reconnect.
References disconnect().
Referenced by disconnect().
get_bd_seq()
uint64_t sparkplug::Publisher::get_bd_seq () const inline nodiscard
Gets the current birth/death sequence number.
Returns
Current bdSeq value (increments on each rebirth, never wraps)
Note
Used by SCADA to detect new sessions/rebirths.
Definition at line 207 of file publisher.hpp.
get_seq()
uint64_t sparkplug::Publisher::get_seq () const inline nodiscard
Gets the current message sequence number.
Returns
Current sequence number (0-255, wraps at 256)
Note
Useful for monitoring and debugging.
Definition at line 196 of file publisher.hpp.
References get_seq().
Referenced by get_seq().
publish_birth()
std::expected< void, std::string > sparkplug::Publisher::publish_birth (PayloadBuilder & payload) nodiscard
Publishes an NBIRTH (Node Birth) message.
The NBIRTH message must be the first message published after connect(). It establishes the session and declares all available metrics with their aliases.
Parameters
payload PayloadBuilder containing metrics with names and aliases
Returns
void on success, error message on failure
Note
The payload should include:
All metrics with both name and alias (for NDATA to use aliases)
bdSeq metric (automatically managed if using rebirth())
Any metadata or properties
Warning
Must be called after connect() and before any publish_data() calls.
See also
publish_data() for subsequent updates
rebirth() for publishing a new NBIRTH during runtime
References publish_birth().
Referenced by publish_birth().
publish_data()
std::expected< void, std::string > sparkplug::Publisher::publish_data (PayloadBuilder & payload) nodiscard
Publishes an NDATA (Node Data) message.
NDATA messages report metric changes by exception. Only include metrics that have changed since the last NDATA message. Uses aliases for bandwidth efficiency (60-80% reduction vs. full names).
Parameters
payload PayloadBuilder containing changed metrics (by alias only)
Returns
void on success, error message on failure
Note
Sequence number is automatically incremented (0-255, wraps at 256).
Timestamp is automatically added if not explicitly set.
Warning
Must call publish_birth() before the first publish_data().
See also
publish_birth() for establishing aliases
References publish_data().
Referenced by publish_data().
publish_death()
std::expected< void, std::string > sparkplug::Publisher::publish_death () nodiscard
Publishes an NDEATH (Node Death) message.
Explicitly sends the NDEATH message. Usually not needed as NDEATH is sent automatically via MQTT Last Will Testament on disconnect or connection loss.
Returns
void on success, error message on failure
Note
Prefer using disconnect() which handles NDEATH automatically.
References publish_death().
Referenced by publish_death().
publish_device_birth()
std::expected< void, std::string > sparkplug::Publisher::publish_device_birth (std::string_view device_id, PayloadBuilder & payload) nodiscard
Publishes a DBIRTH (Device Birth) message.
The DBIRTH message declares a device attached to this edge node. It must be published after NBIRTH and declares all device metrics with aliases.
Parameters
device_id The device identifier (e.g., "Sensor01", "Motor02")
payload PayloadBuilder containing device metrics with names and aliases
Returns
void on success, error message on failure
Note
Device sequence starts at 0 for DBIRTH, then increments for DDATA.
Must call publish_birth() before publishing any device births.
See also
publish_device_data() for subsequent device updates
publish_device_death() for device disconnection
publish_device_command()
std::expected< void, std::string > sparkplug::Publisher::publish_device_command (std::string_view target_edge_node_id, std::string_view target_device_id, PayloadBuilder & payload) nodiscard
Publishes a DCMD (Device Command) message to a device on another edge node.
DCMD messages are commands sent to devices attached to edge nodes.
Parameters
target_edge_node_id The target edge node identifier
target_device_id The target device identifier
payload PayloadBuilder containing command metrics
Returns
void on success, error message on failure
Example Usage
sparkplug::PayloadBuilder cmd;
cmd.add_metric("SetPoint", 75.0);
publisher.publish_device_command("Gateway01", "Motor01", cmd);
publish_device_data()
std::expected< void, std::string > sparkplug::Publisher::publish_device_data (std::string_view device_id, PayloadBuilder & payload) nodiscard
Publishes a DDATA (Device Data) message.
DDATA messages report device metric changes by exception. Only include metrics that have changed since the last DDATA message. Uses aliases for bandwidth efficiency.
Parameters
device_id The device identifier
payload PayloadBuilder containing changed metrics (by alias only)
Returns
void on success, error message on failure
Note
Sequence number is automatically incremented per device (0-255, wraps at 256).
Must call publish_device_birth() before the first publish_device_data().
See also
publish_device_birth() for establishing aliases
publish_device_death()
std::expected< void, std::string > sparkplug::Publisher::publish_device_death (std::string_view device_id) nodiscard
Publishes a DDEATH (Device Death) message.
Explicitly sends a device death message to indicate device disconnection.
Parameters
device_id The device identifier
Returns
void on success, error message on failure
Note
After DDEATH, publish_device_birth() must be called again before DDATA.
publish_node_command()
std::expected< void, std::string > sparkplug::Publisher::publish_node_command (std::string_view target_edge_node_id, PayloadBuilder & payload) nodiscard
Publishes an NCMD (Node Command) message to another edge node.
NCMD messages are commands sent from SCADA/Primary Applications or other edge nodes to request actions like rebirth, reboot, or custom operations.
Parameters
target_edge_node_id The target edge node identifier
payload PayloadBuilder containing command metrics (e.g., "Node Control/Rebirth")
Returns
void on success, error message on failure
Note
Common Node Control commands:
"Node Control/Rebirth" (bool): Request node to republish NBIRTH
"Node Control/Reboot" (bool): Request node to reboot
"Node Control/Next Server" (bool): Switch to backup server
"Node Control/Scan Rate" (int64): Change data acquisition rate
Example Usage
sparkplug::PayloadBuilder cmd;
cmd.add_metric("Node Control/Rebirth", true);
publisher.publish_node_command("Gateway01", cmd);
rebirth()
std::expected< void, std::string > sparkplug::Publisher::rebirth () nodiscard
Triggers a rebirth by publishing a new NBIRTH with incremented bdSeq.
Rebirth is used when:
SCADA/Primary Application requests it via NCMD/Rebirth
New metrics need to be added to the metric inventory
Edge node configuration changes
Returns
void on success, error message on failure
Note
Automatically increments bdSeq and resets sequence number to 0.
Republishes the last NBIRTH payload with updated bdSeq.
Warning
The new NBIRTH should contain ALL metrics (old + new), not just additions.
References rebirth().
Referenced by rebirth().
The documentation for this class was generated from the following file:
include/sparkplug/publisher.hpp