Sparkplug B C++ Library: sparkplug::Subscriber Class Reference
sparkplug::Subscriber Class Reference
Sparkplug B subscriber for consuming edge node messages with validation.
#include <subscriber.hpp>
Classes
struct Config
Configuration parameters for the Sparkplug B subscriber.
struct DeviceState
Tracks the state of a device attached to an edge node.
struct NodeState
Tracks the state of an individual edge node.
Public Member Functions
Subscriber (Config config, MessageCallback callback)
Constructs a Subscriber with the given configuration and callback.
~Subscriber ()
Destroys the Subscriber and cleans up MQTT resources.
Subscriber (const Subscriber &)=delete
Subscriber & operator= (const Subscriber &)=delete
Subscriber (Subscriber &&) noexcept
Subscriber & operator= (Subscriber &&) noexcept
std::expected< void, std::string > connect ()
Connects to the MQTT broker.
std::expected< void, std::string > disconnect ()
Disconnects from the MQTT broker.
std::expected< void, std::string > subscribe_all ()
Subscribes to all Sparkplug B messages for the configured group.
std::expected< void, std::string > subscribe_node (std::string_view edge_node_id)
Subscribes to messages from a specific edge node.
std::expected< void, std::string > subscribe_state (std::string_view host_id)
Subscribes to STATE messages from a primary application.
std::optional< std::reference_wrapper< const NodeState > > get_node_state (std::string_view edge_node_id) const
Gets the current state of a specific edge node.
void set_command_callback (CommandCallback callback)
Sets a callback for receiving command messages (NCMD/DCMD).
void update_node_state (const Topic &topic, const org::eclipse::tahu::protobuf::Payload &payload)
Updates node state tracking (internal use).
Public Attributes
MessageCallback callback_
User-provided callback for received messages.
CommandCallback command_callback_
User-provided callback for received command messages (NCMD/DCMD).
Detailed Description
Sparkplug B subscriber for consuming edge node messages with validation.
The Subscriber class receives and validates Sparkplug B messages:
NBIRTH/DBIRTH: Birth certificates
NDATA/DDATA: Data updates
NDEATH/DDEATH: Death certificates
STATE: Primary application state (optional)
Automatic sequence number validation (detects packet loss)
Node state tracking per edge node
Thread Safety
This class is NOT thread-safe. The callback is invoked on the MQTT thread.
Example Usage
auto callback = [](const sparkplug::Topic& topic,
                   const auto& payload) {
  std::cout << "Received: " << topic.to_string() << "\n";
  for (const auto& metric : payload.metrics()) {
    std::cout << metric.name() << " = " << metric.double_value() << "\n";
  }
};
sparkplug::Subscriber::Config config{
  .broker_url = "tcp://localhost:1883",
  .client_id = "my_subscriber",
  .group_id = "Energy"
};
sparkplug::Subscriber subscriber(std::move(config), callback);
subscriber.connect();
subscriber.subscribe_all();  // Subscribe to all messages in group
// Keep running to receive messages...
See also
Publisher for publishing Sparkplug B messages
Topic for topic namespace parsing
Definition at line 84 of file subscriber.hpp.
Constructor & Destructor Documentation
Subscriber()
sparkplug::Subscriber::Subscriber (Config config, MessageCallback callback)
Constructs a Subscriber with the given configuration and callback.
Parameters
config Subscriber configuration (moved)
callback Function to call for each received message
Note
The callback will be invoked on the MQTT client thread.
Warning
Ensure callback execution is fast to avoid blocking message reception.
Referenced by ~Subscriber().
Member Function Documentation
connect()
std::expected< void, std::string > sparkplug::Subscriber::connect () nodiscard
Connects to the MQTT broker.
Returns
void on success, error message on failure
Note
Must be called before subscribe_all() or subscribe_node().
References connect().
Referenced by connect().
disconnect()
std::expected< void, std::string > sparkplug::Subscriber::disconnect () nodiscard
Disconnects from the MQTT broker.
Returns
void on success, error message on failure
Note
Stops receiving messages after disconnect.
References disconnect().
Referenced by disconnect().
get_node_state()
std::optional< std::reference_wrapper< const NodeState > > sparkplug::Subscriber::get_node_state (std::string_view edge_node_id) const nodiscard
Gets the current state of a specific edge node.
Parameters
edge_node_id The edge node ID to query
Returns
NodeState if the node has been seen, std::nullopt otherwise
Note
Useful for monitoring node online/offline status and bdSeq.
References get_node_state().
Referenced by get_node_state().
set_command_callback()
void sparkplug::Subscriber::set_command_callback (CommandCallback callback)
Sets a callback for receiving command messages (NCMD/DCMD).
Commands are messages sent from SCADA/Primary Applications to edge nodes to trigger actions like rebirth, reboot, or custom operations.
Parameters
callback Function to call when a command is received
Note
The callback is invoked on the MQTT client thread.
Common commands: "Node Control/Rebirth", "Node Control/Reboot", etc.
Example Usage
subscriber.set_command_callback([&publisher](const sparkplug::Topic& topic,
                                             const auto& payload) {
  for (const auto& metric : payload.metrics()) {
    if (metric.name() == "Node Control/Rebirth" && metric.boolean_value()) {
      publisher.rebirth();
    }
  }
});
References set_command_callback().
Referenced by set_command_callback().
subscribe_all()
std::expected< void, std::string > sparkplug::Subscriber::subscribe_all () nodiscard
Subscribes to all Sparkplug B messages for the configured group.
Subscribes to the wildcard topic: spBv1.0/{group_id}/#
This receives all message types (NBIRTH, NDATA, NDEATH, DBIRTH, DDATA, DDEATH) from all edge nodes in the group.
Returns
void on success, error message on failure
Note
Must call connect() first.
The callback will be invoked for every message received.
References subscribe_all().
Referenced by subscribe_all().
subscribe_node()
std::expected< void, std::string > sparkplug::Subscriber::subscribe_node (std::string_view edge_node_id) nodiscard
Subscribes to messages from a specific edge node.
Subscribes to: spBv1.0/{group_id}/+/{edge_node_id}/#
Parameters
edge_node_id The edge node ID to subscribe to
Returns
void on success, error message on failure
Note
More efficient than subscribe_all() if you only need specific nodes.
References subscribe_node().
Referenced by subscribe_node().
subscribe_state()
std::expected< void, std::string > sparkplug::Subscriber::subscribe_state (std::string_view host_id) nodiscard
Subscribes to STATE messages from a primary application.
STATE messages indicate whether a SCADA/Primary Application is online. Subscribe to: STATE/{host_id}
Parameters
host_id The primary application host identifier
Returns
void on success, error message on failure
Note
STATE messages are outside the normal Sparkplug topic namespace.
References subscribe_state().
Referenced by subscribe_state().
update_node_state()
void sparkplug::Subscriber::update_node_state (const Topic & topic, const org::eclipse::tahu::protobuf::Payload & payload)
Updates node state tracking (internal use).
Called automatically from the MQTT callback to update sequence numbers and online status.
Parameters
topic The message topic
payload The message payload
Note
This is public for technical reasons but should not be called directly.
References update_node_state().
Referenced by update_node_state().
Member Data Documentation
callback_
MessageCallback sparkplug::Subscriber::callback_
User-provided callback for received messages.
Note
Public for technical reasons (accessed by static MQTT callback).
Definition at line 257 of file subscriber.hpp.
command_callback_
CommandCallback sparkplug::Subscriber::command_callback_
User-provided callback for received command messages (NCMD/DCMD).
Note
Public for technical reasons (accessed by static MQTT callback).
Definition at line 264 of file subscriber.hpp.
The documentation for this class was generated from the following file:
include/sparkplug/subscriber.hpp